import asyncio, subprocess, uuid
from playwright.async_api import async_playwright
W = "http://localhost:8000"; OUT = "/tmp"; res = []
def check(n, c, i=""):
    res.append((n, bool(c))); print(("PASS " if c else "FAIL ") + n + (f"  [{i}]" if i and not c else ""))
def psql(q): return subprocess.run(["psql","-h","/tmp","-p","5433","-U","postgres","-d","smm6","-tAc",q],capture_output=True,text=True).stdout.strip()
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={"width": 1280, "height": 1000})
        pg = await ctx.new_page(); errs = []; pg.on("pageerror", lambda e: errs.append(str(e)))
        await pg.goto(W + "/login/?mode=register")
        await pg.fill("#email", "mass@example.com"); await pg.fill("#password", "password123"); await pg.click("#submit")
        await pg.wait_for_url("**/dashboard/"); await pg.wait_for_selector("#order-form")
        check("service ID shown in New order", "ID 1" in await pg.inner_text("#svc-list"))
        uid = psql("select id from users where email='mass@example.com'"); tid = str(uuid.uuid4())
        psql(f"insert into topups (id,user_id,amount_php,method,status,credited_at) values ('{tid}',{uid},500,'gcash','credited',now())")
        psql(f"insert into ledger (user_id,delta,reason,ref) values ({uid},500,'topup','{tid}')")
        await pg.goto(W + "/dashboard/#mass"); await pg.wait_for_selector("#mass-form")
        check("mass tab in sidebar", await pg.locator('.side-nav a[data-nav="mass"][aria-current="page"]').count() == 1)
        check("ID list shows services", await pg.locator("#id-list .id-row").count() >= 2)
        await pg.fill("#mass-input", "1|https://tiktok.com/@a|1000\n2|tiktok.com/@b|500\n3|https://instagram.com/p/x|5")
        await pg.check("#mass-ack")
        bad = await pg.locator("#mass-body tr.err-row").count()
        check("preview flags 2 bad lines", bad == 2, bad)
        check("button disabled with errors", await pg.is_disabled("#mass-place") and "Fix 2 lines" in await pg.inner_text("#mass-msg"))
        await pg.screenshot(path=f"{OUT}/mass-errors.png", full_page=True)
        # fix: keep line 1, use ID list to add a line
        await pg.fill("#mass-input", "1|https://tiktok.com/@a|1000")
        await pg.click('#id-list [data-add="2"]')
        val = await pg.input_value("#mass-input")
        check("clicking an ID starts a line", val.endswith("\n2|"), repr(val))
        await pg.type("#mass-input", "https://tiktok.com/@b|500")
        total = await pg.inner_text("#mass-total")
        # 1000 x 73.95/1K = 73.95 ; 500 x 113.59/1K = 56.80 (ceil 56.795) → 130.75
        check("total", total == "₱130.75", total)
        check("button says Place 2 orders", await pg.inner_text("#mass-place") == "Place 2 orders" and not await pg.is_disabled("#mass-place"))
        await pg.click("#mass-place")
        await pg.wait_for_selector("#mass-results .alert")
        txt = await pg.inner_text("#mass-results")
        check("result: placed 2 of 2", "Placed 2 of 2 orders" in txt and "₱130.75" in txt, txt)
        check("textarea cleared", await pg.input_value("#mass-input") == "")
        check("balance updated", "₱369.25" in await pg.inner_text(".balance-card"), await pg.inner_text(".balance-card"))
        await pg.screenshot(path=f"{OUT}/mass-done.png", full_page=True)
        await pg.click(".side-nav a:has-text('Orders')"); await pg.wait_for_selector("#orders-body tr >> text=TikTok")
        check("orders appear", await pg.locator("#orders-body tr").count() == 2)
        m = await b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, storage_state=await ctx.storage_state(), color_scheme="dark")
        mp = await m.new_page(); await mp.goto(W + "/dashboard/#mass"); await mp.wait_for_selector("#mass-form")
        await mp.fill("#mass-input", "1|https://tiktok.com/@a|1000\n2|https://tiktok.com/@b|50")
        sw = await mp.evaluate("document.documentElement.scrollWidth"); check("mobile no h-scroll", sw <= 390, sw)
        check("mobile tabbar has 4 tabs", await mp.locator(".tabbar a").count() == 4)
        await mp.screenshot(path=f"{OUT}/mass-mobile-dark.png", full_page=True)
        await pg.goto(W + "/"); await pg.wait_for_selector("#price-body tr td >> text=TikTok")
        check("landing price table has ID column", (await pg.inner_text("#price-body tr >> nth=0")).strip().startswith("1"))
        check("no page errors", not errs, errs)
        await b.close()
    f = [n for n, ok in res if not ok]; print(f"{len(res)-len(f)}/{len(res)} passed", f or "")
asyncio.run(main())
